steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  # Step 2: Generate static site
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'generate']
    dir: 'frontend'
    env:
      - 'NUXT_PUBLIC_API_BASE=${_API_BASE}'
      - 'NUXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'NUXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'

  # Step 3: Deploy to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil -m rsync -R -d frontend/.output/public/ gs://${_BUCKET_NAME}/

  # Step 4: Invalidate CDN cache
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cdn-cache'
      - '${_URL_MAP_NAME}'
      - '--path=/*'
      - '--async'

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

substitutions:
  _BUCKET_NAME: 'churn-risk-frontend-prod'
  _URL_MAP_NAME: 'churn-risk-frontend-lb'
  _API_BASE: 'https://churn-risk-api-461448724047.us-east1.run.app'
  _FIREBASE_API_KEY: 'AIzaSyAsAfrqGZdfEFpMfA7xPPWGck4l9x3PsCM'
  _FIREBASE_AUTH_DOMAIN: 'churn-risk.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'churn-risk'
