"""add hubspot_updated_at and priority to tickets

Revision ID: 4aa56adc37c1
Revises: c8453b9b7f79
Create Date: 2025-11-09 08:23:06.662921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa56adc37c1'
down_revision = 'c8453b9b7f79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('hubspot_updated_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'hubspot_updated_at')
    # ### end Alembic commands ###
