"""Initial schema

Revision ID: c08085465bad
Revises: 
Create Date: 2025-11-06 21:00:28.659977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c08085465bad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('plan_tier', sa.Enum('STARTER', 'PRO', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    op.create_table('companies',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mrr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('crm_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_tenant_external', 'companies', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HUBSPOT', 'ZENDESK', 'HELPSCOUT', name='integrationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'DISCONNECTED', name='integrationstatus'), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('ticket_topics',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('training_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_topic_name')
    )
    op.create_index(op.f('ix_ticket_topics_tenant_id'), 'ticket_topics', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index('ix_contacts_tenant_external', 'contacts', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('tickets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'OPEN', 'WAITING', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('sentiment_score', sa.Enum('VERY_NEGATIVE', 'NEGATIVE', 'NEUTRAL', 'POSITIVE', 'VERY_POSITIVE', name='sentimentscore'), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_company_id'), 'tickets', ['company_id'], unique=False)
    op.create_index(op.f('ix_tickets_contact_id'), 'tickets', ['contact_id'], unique=False)
    op.create_index(op.f('ix_tickets_sentiment_score'), 'tickets', ['sentiment_score'], unique=False)
    op.create_index('ix_tickets_tenant_external', 'tickets', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_index('ix_tickets_tenant_sentiment', 'tickets', ['tenant_id', 'sentiment_score', 'created_at'], unique=False)
    op.create_table('churn_risk_cards',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('FRUSTRATED', 'SIGNIFICANT_SUPPORT', 'SILENTLY_STRUGGLING', name='triggertype'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'WORKING', 'WAITING', 'COMPLETED', name='churnriskstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churn_risk_cards_company_id'), 'churn_risk_cards', ['company_id'], unique=False)
    op.create_index(op.f('ix_churn_risk_cards_tenant_id'), 'churn_risk_cards', ['tenant_id'], unique=False)
    op.create_index('ix_churn_risks_tenant_status', 'churn_risk_cards', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('ticket_topic_assignments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assigned_by', sa.Enum('AI', 'USER', name='assignedby'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['ticket_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ticket_id', 'topic_id', name='uq_ticket_topic')
    )
    op.create_index('ix_assignments_tenant_ticket', 'ticket_topic_assignments', ['tenant_id', 'ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_topic_assignments_tenant_id'), 'ticket_topic_assignments', ['tenant_id'], unique=False)
    op.create_table('churn_risk_comments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['churn_risk_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churn_risk_comments_card_id'), 'churn_risk_comments', ['card_id'], unique=False)
    op.create_index(op.f('ix_churn_risk_comments_tenant_id'), 'churn_risk_comments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_churn_risk_comments_tenant_id'), table_name='churn_risk_comments')
    op.drop_index(op.f('ix_churn_risk_comments_card_id'), table_name='churn_risk_comments')
    op.drop_table('churn_risk_comments')
    op.drop_index(op.f('ix_ticket_topic_assignments_tenant_id'), table_name='ticket_topic_assignments')
    op.drop_index('ix_assignments_tenant_ticket', table_name='ticket_topic_assignments')
    op.drop_table('ticket_topic_assignments')
    op.drop_index('ix_churn_risks_tenant_status', table_name='churn_risk_cards')
    op.drop_index(op.f('ix_churn_risk_cards_tenant_id'), table_name='churn_risk_cards')
    op.drop_index(op.f('ix_churn_risk_cards_company_id'), table_name='churn_risk_cards')
    op.drop_table('churn_risk_cards')
    op.drop_index('ix_tickets_tenant_sentiment', table_name='tickets')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index('ix_tickets_tenant_external', table_name='tickets')
    op.drop_index(op.f('ix_tickets_sentiment_score'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_contact_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_company_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contacts_tenant_external', table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ticket_topics_tenant_id'), table_name='ticket_topics')
    op.drop_table('ticket_topics')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_index('ix_companies_tenant_external', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
