"""add hubspot_created_at to tickets

Revision ID: c8453b9b7f79
Revises: 9f1cb95f1d24
Create Date: 2025-11-09 08:20:22.918319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8453b9b7f79'
down_revision = '9f1cb95f1d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('hubspot_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'hubspot_created_at')
    # ### end Alembic commands ###
